# Site settings
title: Dave Yates
email: dave.yates@upnorth-it.com
description: > # this means to ignore newlines until "baseurl:"
  One Man, One Keyboard, One Kick Ass Website.
#baseurl: "" 
#url: "http://localhost:4000" # the base hostname & protocol for your site
twitter_username: mahmehtdave
github_username:  dyatesupnorth

# Build settings
markdown: kramdown

authors:
  dave:
    display_name: Dave Yates
    gravatar: 203b7add8948eab434c52d6fd6c81efa
    email: dave.yates@upnorth-it.com
    web: http://www.upnorth-it.com/
    twitter: mahmehtdave
    github: dyatesupnorth
